version: "3.9"

services:

  ow-league-tokens:
    build: .
    entrypoint: [ "python", "./src/main.py", "nomenu", "--owl", "--owc", "--ids", "404727544", "465150740", "402903373", "404970700", "1128139170" ]
    restart: unless-stopped
